apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kn1i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kn1i
    app.kubernetes.io/part-of: tkrw-pr714-0075-0057-app
  name: devfile-sample-kn1i
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kn1i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kn1i
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0057-tenant/tkrw-pr714-0075-0057-app/devfile-sample-kn1i@sha256:06dcf134c9068063fc14c6478b099720ebd01c6641be26b13bcad1cb081e30f8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
